# Generated by Django 3.2.2 on 2021-05-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineChat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messedge',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
