# Generated by Django 3.1.3 on 2021-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
