# Generated by Django 3.1.3 on 2021-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0002_auto_20210128_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
