# Generated by Django 3.1.5 on 2021-02-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0003_auto_20210205_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
