# Generated by Django 3.1.3 on 2021-01-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0003_auto_20210128_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='description',
        ),
    ]
