# Generated by Django 3.1.3 on 2021-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0004_remove_new_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='descript',
            field=models.TextField(null=True),
        ),
    ]
