# Generated by Django 3.1.5 on 2021-02-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0004_auto_20210216_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
