# Generated by Django 3.1.3 on 2021-01-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0005_new_descript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='descript',
            new_name='text',
        ),
    ]
