# Generated by Django 3.1.5 on 2021-02-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0005_auto_20210216_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
